version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - HOST=${HOST}
      - DB_PORT=${DB_PORT}
      - PASS=${PASS}
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"

volumes:
  - .:/usr/src/app
